version: '3.9'
services:
  triton-server:
    build: ./server
    environment:
      - gpus=1
    command: 
      - --model-repository=/models
    network_mode: "host"
  triton-image-client:
    build: ./client/apps/image_client
    network_mode: "host"
    